#bulma_css:
#    resource: "@BulmaCSSBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_profile:
    resource: '@AppBundle/Controller/Panel'
    type: annotation
    prefix: /panel/