# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]

    app.topic_subscriber:
        class: AppBundle\EventListener\TopicSubscriber
        arguments: ["@mailer", "@doctrine.orm.entity_manager", "@templating", "%email_sender%"]
        tags:
         - { name: kernel.event_subscriber }

    app.user_subscriber:
            class: AppBundle\EventListener\UserSubscriber
            arguments: ["@mailer", "@templating", "%email_sender%"]
            tags:
             - { name: kernel.event_subscriber }

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createPanelMenu, alias: panel_menu }

    app.change_password_form:
        class: AppBundle\Form\Panel\ChangePasswordType
        arguments: ["@security.password_encoder", "@security.token_storage"]
        tags:
            - { name: form.type }